# Generated by Django 5.2.1 on 2025-06-12 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='status',
            new_name='spot_status',
        ),
    ]
