# Generated by Django 5.2.1 on 2025-06-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_status_parkingspot_spot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='spot_status',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='status',
            field=models.CharField(choices=[('empty', 'Bo‘sh'), ('occupied', 'Band'), ('reserved', 'Zaxiralangan'), ('maintenance', 'Texnik xizmat')], default='empty', max_length=20),
        ),
    ]
