# Generated by Django 5.2.1 on 2025-06-12 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_parkingspot_spot_status_parkingspot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('card', 'Card'), ('cash', 'Naqd')], default='click', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('success', "To'landi"), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.reservation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
