# Generated by Django 5.2.1 on 2025-06-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
