# Generated by Django 5.2.1 on 2025-06-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_parkingspot_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='user',
        ),
    ]
