# Generated by Django 5.2.1 on 2025-06-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_parkingspot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to='user.parkingzone'),
        ),
    ]
