# Generated by Django 5.2.1 on 2025-06-12 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_parkingspot_zone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reservation_id',
            new_name='reservation',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_id',
            new_name='user',
        ),
    ]
